### PR TITLE
Enable MobiFlight simvars for LEDs and new template for CRJ

### PR DESCRIPTION
**Pull request by bigbrowncow**
Hi Maarten,

I've modified your brilliant tool in two ways

1. Added the MSFS Python SimConnect MobiFlight extension to allow for LVARs to control LEDs. The code is from https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension/blob/main/src/example.py. Presumably this will work for HVARs and other types too but I haven't tested

2. A new config file and template for the CRJ that uses the new LED functionality and more closely matches the layout of the CRJ FCP.

### CODE REVIEW

**Review by maartentamboer — APPROVED** [review]
Looks great, thanks for contributing

**Comment by maartentamboer** [comment]
New release has been made: https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.7.0

**Comment by Koseng** [comment]
Hi guys,

wow open source is impressing me. One of the motivation I wrote the above integrated code was to be able to use it with X-Touch-Mini-FS2020 in the future. And now somebody else integrated it...

Sadly the python simconnect library doesn't seem to be maintained anymore. I also mailed to the guy, cause I made several changes, but he does not answer.

@maartentamboer 
Still it would nice to follow good open source habits and follow the license conditions and mention the usage of my code in some license file on your side.

Thanks guys for your cool work.

**Comment by maartentamboer** [comment]
> @maartentamboer
> Still it would nice to follow good open source habits to adhere the license conditions and mention the usage of my code in some license file on your side.
> 
> https://github.com/Koseng/MSFSPythonSimConnectMobiFlightExtension
> 
> Thanks guys for your cool work.

Ideally your library could be hosted in pypi but that's a pain in the ass to setup. I will definitely credit your stuff and probably change the directly added files to a submodule. I'll let you know once that's done

**Pull request merged**
